/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project5;

import project5.Panels.HomePanel;
import javax.swing.JOptionPane;

/**
 *
 * @author rachelrudolph
 */
public class MainWrapper extends javax.swing.JFrame {

    /**
     * Creates new form MainWrapper
     */
    public MainWrapper() {
        initComponents();
        homePanel.setVisible(true);
        closetPanel.setVisible(false);
        friendsPanel.setVisible(false);
        profilePanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JLabel();
        Navigation = new javax.swing.JPanel();
        ClosetButton = new javax.swing.JButton();
        FriendsButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        UserProfileButton = new javax.swing.JButton();
        SettingsButton = new javax.swing.JButton();
        HelpButton = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        homePanel = new project5.Panels.HomePanel();
        friendsPanel = new project5.Panels.FriendsPanel();
        closetPanel = new project5.Panels.ClosetPanel();
        profilePanel = new project5.Panels.ProfilePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(826, 441));

        Header.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("BORROW");
        Header.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Header.setPreferredSize(new java.awt.Dimension(153, 70));
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeaderMouseClicked(evt);
            }
        });
        getContentPane().add(Header, java.awt.BorderLayout.NORTH);

        Navigation.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ClosetButton.setText("My Closet");
        ClosetButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosetButtonMouseClicked(evt);
            }
        });

        FriendsButton.setText("Friends");
        FriendsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FriendsButtonMouseClicked(evt);
            }
        });

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        UserProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/001-avatar-inside-a-circle.png"))); // NOI18N
        UserProfileButton.setText("Jane Smith");
        UserProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        UserProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserProfileButtonActionPerformed(evt);
            }
        });

        SettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/002-settings.png"))); // NOI18N
        SettingsButton.setText("Settings");
        SettingsButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SettingsButtonActionPerformed(evt);
            }
        });

        HelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/001-info.png"))); // NOI18N
        HelpButton.setText("Help");
        HelpButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NavigationLayout = new javax.swing.GroupLayout(Navigation);
        Navigation.setLayout(NavigationLayout);
        NavigationLayout.setHorizontalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ClosetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(FriendsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavigationLayout.createSequentialGroup()
                .addGroup(NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HelpButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SettingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserProfileButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        NavigationLayout.setVerticalGroup(
            NavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationLayout.createSequentialGroup()
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClosetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FriendsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SettingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HelpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(Navigation, java.awt.BorderLayout.WEST);

        MainPanel.setMaximumSize(new java.awt.Dimension(703, 371));
        MainPanel.setMinimumSize(new java.awt.Dimension(703, 371));
        MainPanel.setPreferredSize(new java.awt.Dimension(703, 371));
        MainPanel.setLayout(new javax.swing.OverlayLayout(MainPanel));
        MainPanel.add(homePanel);
        MainPanel.add(friendsPanel);
        MainPanel.add(closetPanel);
        MainPanel.add(profilePanel);

        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClosetButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosetButtonMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        closetPanel.setVisible(true);
        friendsPanel.setVisible(false);
        profilePanel.setVisible(false);
    }//GEN-LAST:event_ClosetButtonMouseClicked

    private void FriendsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FriendsButtonMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(false);
        closetPanel.setVisible(false);
        friendsPanel.setVisible(true);
        profilePanel.setVisible(false);
    }//GEN-LAST:event_FriendsButtonMouseClicked

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        MainWrapper home = new MainWrapper();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void HeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(true);
        closetPanel.setVisible(false);
        friendsPanel.setVisible(false);
        profilePanel.setVisible(false);
    }//GEN-LAST:event_HeaderMouseClicked

    private void UserProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserProfileButtonActionPerformed
        // TODO add your handling code here:
        homePanel.setVisible(false);
        closetPanel.setVisible(false);
        friendsPanel.setVisible(false);
        profilePanel.setVisible(true);
    }//GEN-LAST:event_UserProfileButtonActionPerformed

    private void SettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SettingsButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
            "Settings will be implemented in later version.");
    }//GEN-LAST:event_SettingsButtonActionPerformed

    private void HelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
            "Help will be implemented in later version.");
    }//GEN-LAST:event_HelpButtonActionPerformed

    private void homePanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homePanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_homePanelComponentHidden

    private void homePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homePanelComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_homePanelComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWrapper.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWrapper().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClosetButton;
    private javax.swing.JButton FriendsButton;
    private javax.swing.JLabel Header;
    private javax.swing.JButton HelpButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Navigation;
    private javax.swing.JButton SettingsButton;
    private javax.swing.JButton UserProfileButton;
    private project5.Panels.ClosetPanel closetPanel;
    private project5.Panels.FriendsPanel friendsPanel;
    private project5.Panels.HomePanel homePanel;
    private project5.Panels.ProfilePanel profilePanel;
    // End of variables declaration//GEN-END:variables
}
