/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project5.Panels;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import project5.utilities.TextPrompt;
/**
 *
 * @author rachelrudolph
 */
public class FriendsPanel extends javax.swing.JPanel {
    TextPrompt tp1;

    /**
     * Creates new form HomePanel
     */
    public FriendsPanel() {
        initComponents();
        CategoryPanel.setVisible(true);
        KappaSigPanel.setVisible(false);
        FootballPanel.setVisible(false);
        RoommatesPanel.setVisible(false);
        PalsPanel.setVisible(false);
        
        this.tp1 = new TextPrompt( "Search Friends...", jTextField1);
        this.tp1.setShow(TextPrompt.Show.FOCUS_LOST);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        CategoryPanel = new javax.swing.JPanel();
        KappaSig = new javax.swing.JButton();
        Roommates = new javax.swing.JButton();
        FootballTeam = new javax.swing.JButton();
        Pals = new javax.swing.JButton();
        AddCategory = new javax.swing.JButton();
        FootballPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RoommatesPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PalsPanel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        KappaSigPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(703, 371));
        setPreferredSize(new java.awt.Dimension(703, 405));
        setLayout(new java.awt.BorderLayout());

        MainPanel.setMaximumSize(new java.awt.Dimension(702, 326));
        MainPanel.setLayout(new javax.swing.OverlayLayout(MainPanel));

        CategoryPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CategoryPanel.setLayout(new java.awt.GridLayout(3, 3));

        KappaSig.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        KappaSig.setText("ΚΣ");
        KappaSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KappaSigActionPerformed(evt);
            }
        });
        CategoryPanel.add(KappaSig);

        Roommates.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Roommates.setText("Roommates");
        Roommates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoommatesActionPerformed(evt);
            }
        });
        CategoryPanel.add(Roommates);

        FootballTeam.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        FootballTeam.setText("Football Team");
        FootballTeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FootballTeamActionPerformed(evt);
            }
        });
        CategoryPanel.add(FootballTeam);

        Pals.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Pals.setText("Pals");
        Pals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PalsActionPerformed(evt);
            }
        });
        CategoryPanel.add(Pals);

        AddCategory.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AddCategory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/add-512.png"))); // NOI18N
        AddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCategoryActionPerformed(evt);
            }
        });
        CategoryPanel.add(AddCategory);

        MainPanel.add(CategoryPanel);

        FootballPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        FootballPanel.setPreferredSize(new java.awt.Dimension(711, 343));
        FootballPanel.setLayout(new java.awt.GridLayout(2, 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel1.setText("Jimmy");
        FootballPanel.add(jLabel1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel2.setText("Bobby");
        FootballPanel.add(jLabel2);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel3.setText("Danny");
        FootballPanel.add(jLabel3);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel6.setText("Davey");
        FootballPanel.add(jLabel6);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel7.setText("Sammy");
        FootballPanel.add(jLabel7);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel8.setText("Roberto");
        FootballPanel.add(jLabel8);

        MainPanel.add(FootballPanel);

        RoommatesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RoommatesPanel.setPreferredSize(new java.awt.Dimension(711, 343));
        RoommatesPanel.setLayout(new java.awt.GridLayout(2, 3));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel4.setText("Jimmy");
        RoommatesPanel.add(jLabel4);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel5.setText("Bobby");
        RoommatesPanel.add(jLabel5);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel9.setText("Danny");
        RoommatesPanel.add(jLabel9);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel10.setText("Davey");
        RoommatesPanel.add(jLabel10);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel11.setText("Sammy");
        RoommatesPanel.add(jLabel11);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel12.setText("Roberto");
        RoommatesPanel.add(jLabel12);

        MainPanel.add(RoommatesPanel);

        PalsPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PalsPanel.setPreferredSize(new java.awt.Dimension(711, 343));
        PalsPanel.setLayout(new java.awt.GridLayout(2, 3));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel13.setText("Jimmy");
        PalsPanel.add(jLabel13);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel14.setText("Bobby");
        PalsPanel.add(jLabel14);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel15.setText("Danny");
        PalsPanel.add(jLabel15);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel16.setText("Davey");
        PalsPanel.add(jLabel16);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel17.setText("Sammy");
        PalsPanel.add(jLabel17);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel18.setText("Roberto");
        PalsPanel.add(jLabel18);

        MainPanel.add(PalsPanel);

        KappaSigPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        KappaSigPanel.setPreferredSize(new java.awt.Dimension(711, 343));
        KappaSigPanel.setLayout(new java.awt.GridLayout(2, 3));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel19.setText("Jimmy");
        KappaSigPanel.add(jLabel19);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel20.setText("Bobby");
        KappaSigPanel.add(jLabel20);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel21.setText("Danny");
        KappaSigPanel.add(jLabel21);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel22.setText("Davey");
        KappaSigPanel.add(jLabel22);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel23.setText("Sammy");
        KappaSigPanel.add(jLabel23);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project5/Images/icon.png"))); // NOI18N
        jLabel24.setText("Roberto");
        KappaSigPanel.add(jLabel24);

        MainPanel.add(KappaSigPanel);

        add(MainPanel, java.awt.BorderLayout.CENTER);

        SearchPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(SearchPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Object[] options = {"Yes I do!", "No I don't :("};
        int n = JOptionPane.showOptionDialog(this,
            "Do you want to borrow this black belt?", "",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            options,options);
        jButton1.setText("Pending");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void KappaSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KappaSigActionPerformed
        // TODO add your handling code here:
        CategoryPanel.setVisible(false);
        KappaSigPanel.setVisible(true);
        FootballPanel.setVisible(false);
        RoommatesPanel.setVisible(false);
        PalsPanel.setVisible(false);
    }//GEN-LAST:event_KappaSigActionPerformed

    private void RoommatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoommatesActionPerformed
        // TODO add your handling code here:
        CategoryPanel.setVisible(false);
        KappaSigPanel.setVisible(false);
        FootballPanel.setVisible(false);
        RoommatesPanel.setVisible(true);
        PalsPanel.setVisible(false);
    }//GEN-LAST:event_RoommatesActionPerformed

    private void FootballTeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FootballTeamActionPerformed
        // TODO add your handling code here:
        CategoryPanel.setVisible(false);
        KappaSigPanel.setVisible(false);
        FootballPanel.setVisible(true);
        RoommatesPanel.setVisible(false);
        PalsPanel.setVisible(false);
    }//GEN-LAST:event_FootballTeamActionPerformed

    private void PalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PalsActionPerformed
        // TODO add your handling code here:
        CategoryPanel.setVisible(false);
        KappaSigPanel.setVisible(false);
        FootballPanel.setVisible(false);
        RoommatesPanel.setVisible(false);
        PalsPanel.setVisible(true);
    }//GEN-LAST:event_PalsActionPerformed

    private void AddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCategoryActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, 
            "In future version you will be able to add friend category.");
    }//GEN-LAST:event_AddCategoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCategory;
    private javax.swing.JPanel CategoryPanel;
    private javax.swing.JPanel FootballPanel;
    private javax.swing.JButton FootballTeam;
    private javax.swing.JButton KappaSig;
    private javax.swing.JPanel KappaSigPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton Pals;
    private javax.swing.JPanel PalsPanel;
    private javax.swing.JButton Roommates;
    private javax.swing.JPanel RoommatesPanel;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
